# Generated by Django 5.1.7 on 2025-04-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_options_alter_customuser_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Изображение должно быть квадратным (рекомендуемый размер 200x200)",
                null=True,
                upload_to="avatars/",
                verbose_name="Изображение пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Введите страну"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                verbose_name="Введите адрес электронной почты",
            ),
        ),
    ]
