# Generated by Django 5.1.7 on 2025-04-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["title"],
                "permissions": [
                    ("can_add_blog", "Can add blog"),
                    ("can_change_blog", "Can change blog"),
                    ("can_delete_blog", "Can delete blog"),
                    ("can_view_blog", "Can view blog"),
                ],
                "verbose_name": "блог",
                "verbose_name_plural": "блоги",
            },
        ),
    ]
