# Generated by Django 5.1.7 on 2025-04-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["title"],
                "permissions": [
                    ("can_add_blog", "Может добавлять статьи"),
                    ("can_change_blog", "Может изменять статьи"),
                    ("can_delete_blog", "Может удалять статьи"),
                    ("can_view_blog", "Может просматривать статьи"),
                    (
                        "can_view_unpublished",
                        "Может просматривать неопубликованные статьи",
                    ),
                    ("can_publish_blog", "Может публиковать статьи"),
                ],
                "verbose_name": "блог",
                "verbose_name_plural": "блоги",
            },
        ),
    ]
