# Generated by Django 5.1.7 on 2025-03-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("address", models.TextField(verbose_name="Адрес")),
            ],
            options={
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
                "ordering": ["name"],
            },
        ),
    ]
