# Generated by Django 5.1.7 on 2025-04-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, чтобы опубликовать продукт",
                verbose_name="Опубликован",
            ),
        ),
    ]
