# Generated by Django 5.1.7 on 2025-05-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
